// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8iz0wu4mAi-m9n4IUqbx7YInWiMQEooM',
    appId: '1:251038220230:web:d73a04c085fcbcc7953cc7',
    messagingSenderId: '251038220230',
    projectId: 'todo-is-cool',
    authDomain: 'todo-is-cool.firebaseapp.com',
    storageBucket: 'todo-is-cool.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJeodHEbphh_L5uPXydn1nU2IIA8H65Nw',
    appId: '1:251038220230:android:05127c32522d06f3953cc7',
    messagingSenderId: '251038220230',
    projectId: 'todo-is-cool',
    storageBucket: 'todo-is-cool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsBuNFFFM8csGnY_7Pr0q7k0r_EAJUZtQ',
    appId: '1:251038220230:ios:836c8afdc2451325953cc7',
    messagingSenderId: '251038220230',
    projectId: 'todo-is-cool',
    storageBucket: 'todo-is-cool.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsBuNFFFM8csGnY_7Pr0q7k0r_EAJUZtQ',
    appId: '1:251038220230:ios:836c8afdc2451325953cc7',
    messagingSenderId: '251038220230',
    projectId: 'todo-is-cool',
    storageBucket: 'todo-is-cool.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8iz0wu4mAi-m9n4IUqbx7YInWiMQEooM',
    appId: '1:251038220230:web:96f17a381c5af3a1953cc7',
    messagingSenderId: '251038220230',
    projectId: 'todo-is-cool',
    authDomain: 'todo-is-cool.firebaseapp.com',
    storageBucket: 'todo-is-cool.firebasestorage.app',
  );
}
