name: my_weather_app
description: "A responsive cross-platform OpenWeather application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  url_launcher: ^6.3.0
  connectivity_plus: ^7.1.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
