# android/gradle.properties

# Forces Gradle to save and read all its downloaded dependencies on your D drive
gradle.user.home=D:/.gradle_cache_root

# Maintain conservative low-RAM limiters for your system stability
org.gradle.workers.max=2
org.gradle.parallel=false
org.gradle.jvmargs=-Xmx1536m -XX:+UseSerialGC -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx1024m -XX:+UseSerialGC

android.useAndroidX=true
android.enableJetifier=true
android.newDsl=false
android.builtInKotlin=false
